"""migration

Revision ID: 97ea13ac849f
Revises: 
Create Date: 2021-07-15 05:30:19.897830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ea13ac849f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foodName', sa.String(length=100), nullable=True),
    sa.Column('foodPrice', sa.String(length=100), nullable=True),
    sa.Column('foodQuantity', sa.String(length=100), nullable=True),
    sa.Column('foodDescription', sa.Text(), nullable=True),
    sa.Column('foodImage', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foodName', sa.String(length=100), nullable=True),
    sa.Column('foodQuantity', sa.String(length=100), nullable=True),
    sa.Column('foodPrice', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav_foods',
    sa.Column('fav_food_id', sa.Integer(), nullable=False),
    sa.Column('foodName', sa.String(length=100), nullable=True),
    sa.Column('foodImage', sa.Text(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('fav_food_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_foods')
    op.drop_table('user')
    op.drop_table('orders')
    op.drop_table('foods')
    # ### end Alembic commands ###
